name: Bug report
description: Report a reproducible bug in the project
title: "[Bug]: "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Please provide enough information so we can reproduce and fix the issue.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Describe the bug clearly.
      placeholder: What happened? What is broken?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected result.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what you experienced.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, and version (if relevant)
      placeholder: "Windows 11 / Chrome 122"

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Add logs or screenshots if available.
      placeholder: Drag and drop images or paste logs here.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any extra information that might help.
      placeholder: Optional
